### ISSUE TITLE
Misleading report for check 6.9

### ISSUE THREAD

**Issue by AlexDieRobbe** [klouddb/klouddbshield#11]
The postgresSQL pgcrypto is not set in my test run.

The following result appears however in the report:
![klouddbshield pgcrypto OK even if failed](https://github.com/user-attachments/assets/7052a612-df5d-4bc9-bdf4-14eb8a904e73)

The icon is misleading as the check 6.9 does not pass. It is described in its content: the fail reason is provided.

**Comment by klouddb** [comment]
@AlexDieRobe Will test this and get back to you

**Comment by klouddb** [comment]
@AlexDieRobe Thank you for reporting this issue. We've tested it and will have a fix in the next release, with an estimated timeline around October 15th

**Comment by klouddb** [comment]
@AlexDieRobe  We fixed this issue in new release (released yesterday).. Also we released new features like SSL check etc.. Please validate and let us know if you still notice issues

**Comment by klouddb** [comment]
Issue resolved

**Comment by AlexDieRobbe** [comment]
Thanks for the work. It seems to be good now.
