### ISSUE TITLE
Other credentials reported than the kshieldconfig.toml

### ISSUE THREAD

**Issue by AlexDieRobbe** [klouddb/klouddbshield#8]
## Description

Thanks for your work as it helps hardening our PostgresDB!

I might have run into a special case while running it with "All Postgres checks". The full scan runs with the following toml configuration
```
[postgres]
host="localhost"
port="5432"
user="postgres"
dbname="mydb_user"
password="somerandomsecurepassword"
maxIdleConn=2
maxOpenConn=2
```

throws an error
```
2024/09/03 08:54:14 failed to connect to postgres: pq: no pg_hba.conf entry for host "192.168.65.1", user "postgres", database "postgres", no encryption
```

The postgres report is provided. The report contains results for `Postgres Checks` und `HBA checks`. There is also the log parser summary.

I don't know if there is something wrong in my configuration or if it is only a wrong log output.

**Comment by klouddb** [comment]
@AlexDieRobe It appears there may be an issue with the HBA configuration. Please verify that the correct HBA entry is present for the server(check your hba file)

**Comment by AlexDieRobbe** [comment]
It seems the HBA entry was not consistent indeed. Sorry for the false positive.

**Comment by klouddb** [comment]
@AlexDieRobe Not a problem at all. If you encounter any other issues, feel free to reach out. We're happy to assist!
