### ISSUE TITLE
JSON Output not Working

### ISSUE THREAD

**Issue by quentinkhoo** [klouddb/klouddbshield#9]
Hello all! Thank you for the work on this! 

Just wondering, is it possible to output results in JSON? I see that even though the output resulting file is `rdssecreport.json`, I still get a table format. For context this was the command I ran `ciscollector -r -output-type json` and I ran this against the `AWS RDS Sec Report` option

```
root@ac223b16a220:~# ciscollector -r -output-type json
 1: All Postgres checks(Recommended)
 2: Postgres CIS and User Security checks
 3: HBA Scanner
 4: Postgres PII report
 5: Inactive user report
 6: Client ip report
 7: HBA unused lines report
 8: Password Manager
 9: Password leak scanner
10: AWS RDS Sec Report
11: AWS Aurora Sec Report
12: MySQL Report
13: Transaction Wraparound Report
14: Exit

Enter your choice to execute(from 1 to 14):10
```

But for some reason my results are still in `table` format and not JSON.

```
% cat rdssecreport.json


┌───────┬──────────────────────────────────────────────────────────────────────┬────────┐
│ Ctrl  │ Title                                                                │ Status │
├───────┼──────────────────────────────────────────────────────────────────────┼────────┤
│ 2.3.1 │ Ensure that encryption is enabled for RDS instances                  │ Fail   │
├───────┼──────────────────────────────────────────────────────────────────────┼────────┤
│ 2.3.2 │ Ensure that auto minor version upgrade is enabled for RDS instances  │ Fail   │
├───────┼──────────────────────────────────────────────────────────────────────┼────────┤
│ 2.3.3 │ Ensure that public address is not given to RDS instance              │ Pass   │
├───────┼──────────────────────────────────────────────────────────────────────┼────────┤
│ 3.5.0 │ Multi-AZ check                                                       │ Fail   │
├───────┼──────────────────────────────────────────────────────────────────────┼────────┤
│ 3.8.0 │ Ensure Relational Database Service backup retention policy is set    │ Pass   │
├───────┼──────────────────────────────────────────────────────────────────────┼────────┤
│ 4.2.0 │ Ensure SNS topic is created for RDS events                           │ Pass   │
├───────┼──────────────────────────────────────────────────────────────────────┼────────┤
│ 4.3.0 │ Ensure RDS event subscriptions are enabled for Instance level events │ Fail   │
├───────┼──────────────────────────────────────────────────────────────────────┼────────┤
│ 4.4.0 │ Ensure RDS event subscriptions are enabled for DB security groups    │ Fail   │
└───────┴──────────────────────────────────────────────────────────────────────┴────────┘
```

If it matters, this is my `ciscollector --version`
```
root@ac223b16a220:~# ciscollector --version
Thu, 05 Sep 2024 18:16:29 +0800 DBG ../home/runner/work/klouddbshield/klouddbshield/pkg/config/config.go:350 > version=2.0
```

**Comment by klouddb** [comment]
@quentinkhoo Are you seeing this for RDS report only ? Did you try Postgres report ?

**Comment by quentinkhoo** [comment]
> @quentinkhoo Are you seeing this for RDS report only ? Did you try Postgres report ?

@klouddb Yep unfortunately I have the same issue the Postgres reports as well, can't seem to get a json formated report.

**Comment by klouddb** [comment]
@quentinkhoo We have verified this and found that the JSON output is currently available only for the log parser feature. We plan to add JSON output support for other features in future releases

**Comment by klouddb** [comment]
@quentinkhoo We added JSON output in new release (released yesterday).. Also we introduced new features like SSL check etc.. Also you can specify custom path for your config file now

**Comment by klouddb** [comment]
@quentinkhoo  Here are the flags you need to use ciscollector -r --output-type json --config ./ 

1) To specify custom config file path use --config flag 2) To specify JSON type use --output-type json .. Please try these two flags and let us know

**Comment by quentinkhoo** [comment]
hey @klouddb , thanks for the update! I can confirm that I can 
1. Get a json report output from the `--output-type json` flag
2. Pass in a custom config file with `--config` flag.

that being said though it seems like I still have the problem of establishing a connection by default if my DB is expected to connect through SSL. Personally it works for me when I comment this [line](https://github.com/klouddb/klouddbshield/blame/81b0eb697058c035c5cfd301053d19a0457712ed/pkg/postgresdb/connect.go#L18) out and modify [line 38](https://github.com/klouddb/klouddbshield/blob/8d0c5cf3f83fa118ae0cde529a05da688414b220/pkg/postgresdb/connect.go#L38) and pass this in as a value in the config file.

In addition, if my RDS Security Group doesn't accept ICMP traffic, [the ping check defined here](https://github.com/klouddb/klouddbshield/blob/81b0eb697058c035c5cfd301053d19a0457712ed/pkg/postgresdb/connect.go#L81) would fail as well 😅
